# Token didapat dari: terraform output node1_tunnel_token
node1_token: "{{ lookup('env', 'NODE1_TUNNEL_TOKEN') }}"

# Token didapat dari: terraform output node2_tunnel_token
node2_token: "{{ lookup('env', 'NODE2_TUNNEL_TOKEN') }}"

# Konfigurasi Disk (Digunakan untuk labeling)
# Pastikan variabel ini sinkron dengan inventory.ini
disk_type: "{{ 'ssd' if inventory_hostname == 'node1' else 'hdd' }}"