apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: victoria-logs
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - hdd
      containers:
      - name: victoria-logs
        image: victoriametrics/victoria-logs:v1.99.0
        args:
          - "-storageDataPath=/storage"
          - "-retentionPeriod=1"
        ports:
          - containerPort: 8428
        volumeMounts:
          - name: logs-storage
            mountPath: /vlogs-data
      volumes:
        - name: logo-storage
          hostPath:
            path: /mnt/storage-hdd/vlogs